# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: hbally <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/11/24 19:31:29 by hbally            #+#    #+#              #
#    Updated: 2018/12/05 09:48:24 by hbally           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

run : 
	make test -C ../../
	cp ../fillit ./
	clear
	./fillit ./bad_1tetro_badformat1
	./fillit ./bad_1tetro_badformat2
	./fillit ./bad_1tetro_badformat3
	./fillit ./bad_1tetro_badformat4
	./fillit ./bad_1tetro_badformat5
	./fillit ./bad_1tetro_badformat6
	./fillit ./bad_1tetro_badformat7
	./fillit ./bad_1tetro_badformat8
	./fillit ./bad_1tetro_badshape1
	./fillit ./bad_1tetro_badshape10
	./fillit ./bad_1tetro_badshape11
	./fillit ./bad_1tetro_badshape12
	./fillit ./bad_1tetro_badshape13
	./fillit ./bad_1tetro_badshape2
	./fillit ./bad_1tetro_badshape3
	./fillit ./bad_1tetro_badshape4
	./fillit ./bad_1tetro_badshape5
	./fillit ./bad_1tetro_badshape6
	./fillit ./bad_1tetro_badshape7
	./fillit ./bad_1tetro_badshape8
	./fillit ./bad_1tetro_badshape9
	./fillit ./bad_empty
	./fillit ./bad_long_1
	./fillit ./bad_long_10
	./fillit ./bad_long_11
	./fillit ./bad_long_12
	./fillit ./bad_long_13
	./fillit ./bad_long_2
	./fillit ./bad_long_3
	./fillit ./bad_long_4
	./fillit ./bad_long_5
	./fillit ./bad_long_6
	./fillit ./bad_long_7
	./fillit ./bad_long_8
	./fillit ./bad_long_9
	./fillit ./bad_newlines
	./fillit ./bad_oneline_1char
	./fillit ./bad_oneline_4chars
	./fillit ./bad_oneline_nonewline
	./fillit ./bad_oneline_text
	./fillit ./bad_oneline_text_4chars
	./fillit ./bad_long_27tetros
	./fillit ./bad_long_+27tetros
	./fillit ./bad_links
	./fillit ./bad_links1
	./fillit ./bad_links10
	./fillit ./bad_links11
	./fillit ./bad_links12
	./fillit ./bad_links2
	./fillit ./bad_links3
	./fillit ./bad_links4
	./fillit ./bad_links5
	./fillit ./bad_links6
	./fillit ./bad_links7
	./fillit ./bad_links8
	./fillit ./bad_links9
